# Site settings
title: LTR Runbooks
description: Documentation for LTR Runbooks
logo: "/assets/pinglogo.jpeg"

# Theme settings
remote_theme: pmarsceill/just-the-docs
color_scheme: dark

# Plugins
plugins:
  - jekyll-remote-theme

# Search settings
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10


nav_enabled: true